# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/39395e03-9753-48ba-9161-22a0c927d682";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/39395e03-9753-48ba-9161-22a0c927d682";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/39395e03-9753-48ba-9161-22a0c927d682";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/39395e03-9753-48ba-9161-22a0c927d682";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/persistent" =
    { device = "/dev/disk/by-uuid/39395e03-9753-48ba-9161-22a0c927d682";
      fsType = "btrfs";
      options = [ "subvol=@persistent" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/39395e03-9753-48ba-9161-22a0c927d682";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/39395e03-9753-48ba-9161-22a0c927d682";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/898E-C12E";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.hypervGuest.enable = true;
}
