# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = 
    { device = "/dev/disk/by-uuid/58AB-2D9D";
      fsType = "vfat";
      options = [ "umask=0077" ];
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/938c0fb9-e49e-44e1-b538-1a1f9276d0af";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/938c0fb9-e49e-44e1-b538-1a1f9276d0af";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/938c0fb9-e49e-44e1-b538-1a1f9276d0af";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/938c0fb9-e49e-44e1-b538-1a1f9276d0af";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/persistent" =
    { device = "/dev/disk/by-uuid/938c0fb9-e49e-44e1-b538-1a1f9276d0af";
      fsType = "btrfs";
      options = [ "subvol=@persistent" ];
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/938c0fb9-e49e-44e1-b538-1a1f9276d0af";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/938c0fb9-e49e-44e1-b538-1a1f9276d0af";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  swapDevices = [ 
    {
      device = "/swap/swapfile";
      size = 10240;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
