# There are no space before and after =
# busctl --user call   org.fcitx.Fcitx5   /controller   org.fcitx.Fcitx.Controller1   ReloadAddonConfig   s classicui
# Use this to reload directly.
Vertical Candidate List=True
PerScreenDPI=False
WheelForPaging=False
Font="Source Han Serif 14"
MenuFont="Source Han Serif 14"
TrayFont="Source Han Serif 14"
Theme=mint-blue-dark
EnableFractionalScale=True


